name: 🚀 Deploy - TW Tools 

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_master:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Build with secrets variables
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            npm install -g yarn
            yarn install --frozen-lockfile
            yarn build

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Deploy to FTP Server (master)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
            server: ${{secrets.FTP_HOST}}
            username: ${{ secrets.FTP_LOGIN }}
            password: ${{ secrets.FTP_PASSWORD }}
            local-dir: out/
            server-dir: /public_html/
            state-name: .ftp-deploy-sync-state.json